### ISSUE TITLE
Misinformation in the readme

### ISSUE THREAD

**Issue by P3qch** [AMZGstudio/ACREngine#1]
Sooo you said it's compatible with pretty much every platform, but after taking a glance in you code it seems that you are using `windows.h` basically meaning this will work only on windows :D I understand that you tried to make non windows users just not use the windows function, but yet the `#include <windows.h>` doesn't seem to be filtered out for non windows systems. so yeh

**Comment by AMZGstudio** [comment]
You are indeed correct, I am going to change that in the next release. What I meant Is that it uses the standard ANSI escape sequences, so all that would need to be changed for other platforms is the input and output, not the actual code render, drawing functions, or the buffer. I used windows to handle the input/output stuff. but if you want to use Linux, there isn't much you would have to change.
